lab-guide.pdf: lab-guide.tex header.tex
	pdflatex -jobname=lab-guide lab-guide
	pdflatex -jobname=lab-guide lab-guide

clean:
	rm -fr auto
	rm -f lab-guide.aux lab-guide.log lab-guide.pdf lab-guide.dvi lab-guide.out
